FROM maven:3.9.8-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY pom.xml .
COPY common common
COPY scheduler-core scheduler-core
COPY database database
COPY kafka kafka
COPY redis redis
COPY api-server api-server
COPY job-service job-service
COPY search-service search-service
COPY watcher-service watcher-service
COPY consumer-service consumer-service
COPY executor-service executor-service

RUN mvn -pl api-server -am package dependency:copy-dependencies -DincludeScope=runtime -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /workspace/api-server/target /app/target

EXPOSE 8080

ENTRYPOINT ["java","-cp","/app/target/classes:/app/target/dependency/*","com.project.scheduler.api.ApiServerApplication"]
